// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at c5d7a2917bc0cf0a27bed802a3664c0bf3d5bf8b
//
#![recursion_limit = "2048"]
#![no_std]
pub mod defines;
pub mod dma_ctrl;
pub mod doe_mbox;
pub mod el2_pic_ctrl;
pub mod fifo_regs;
pub mod fuses;
pub mod i3c;
pub mod interface_regs;
pub mod lc_ctrl;
pub mod mbox;
pub mod mci;
pub mod otp_ctrl;
pub mod primary_flash_ctrl;
pub mod secondary_flash_ctrl;
pub mod sha512_acc;
pub mod soc;
