// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at c5d7a2917bc0cf0a27bed802a3664c0bf3d5bf8b
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
