// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at c5d7a2917bc0cf0a27bed802a3664c0bf3d5bf8b
//
#[allow(unused_imports)]
use tock_registers::interfaces::{Readable, Writeable};
pub trait FifoRegsPeripheral {
    fn set_dma_ram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn set_dma_rom_sram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn register_event_channels(
        &mut self,
        _events_to_caliptra: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_caliptra: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
        _events_to_mcu: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_mcu: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
    ) {
    }
    fn poll(&mut self) {}
    fn warm_reset(&mut self) {}
    fn update_reset(&mut self) {}
    fn read_log_fifo_data(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::fifo_regs::bits::LogFifoData::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_log_fifo_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::fifo_regs::bits::LogFifoStatus::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_itrng_fifo_data(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_itrng_fifo_data(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_itrng_fifo_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::fifo_regs::bits::ItrngFifoStatus::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_itrng_fifo_status(
        &mut self,
        _val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::fifo_regs::bits::ItrngFifoStatus::Register,
        >,
    ) {
    }
    fn read_dbg_fifo_pop(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn read_dbg_fifo_push(&mut self) -> caliptra_emu_types::RvData {
        0
    }
    fn write_dbg_fifo_push(&mut self, _val: caliptra_emu_types::RvData) {}
    fn read_dbg_fifo_status(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::fifo_regs::bits::DbgFifoStatus::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
}
pub struct FifoRegsBus {
    pub periph: Box<dyn FifoRegsPeripheral>,
}
impl caliptra_emu_bus::Bus for FifoRegsBus {
    fn read(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
    ) -> Result<caliptra_emu_types::RvData, caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::LoadAddrMisaligned);
        }
        match addr {
            0..4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_log_fifo_data().reg.get(),
            )),
            4..8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_log_fifo_status().reg.get(),
            )),
            8..0xc => Ok(self.periph.read_itrng_fifo_data()),
            0xc..0x10 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_itrng_fifo_status().reg.get(),
            )),
            0x10..0x14 => Ok(self.periph.read_dbg_fifo_pop()),
            0x14..0x18 => Ok(self.periph.read_dbg_fifo_push()),
            0x18..0x1c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_dbg_fifo_status().reg.get(),
            )),
            _ => Err(caliptra_emu_bus::BusError::LoadAccessFault),
        }
    }
    fn write(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
        val: caliptra_emu_types::RvData,
    ) -> Result<(), caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::StoreAddrMisaligned);
        }
        match addr {
            8..0xc => {
                self.periph.write_itrng_fifo_data(val);
                Ok(())
            }
            0xc..0x10 => {
                self.periph
                    .write_itrng_fifo_status(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x14..0x18 => {
                self.periph.write_dbg_fifo_push(val);
                Ok(())
            }
            _ => Err(caliptra_emu_bus::BusError::StoreAccessFault),
        }
    }
    fn poll(&mut self) {
        self.periph.poll();
    }
    fn warm_reset(&mut self) {
        self.periph.warm_reset();
    }
    fn update_reset(&mut self) {
        self.periph.update_reset();
    }
}
