// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at c5d7a2917bc0cf0a27bed802a3664c0bf3d5bf8b
//
pub mod dma;
pub mod doe_mbox;
pub mod el2_pic;
pub mod fifo_regs;
pub mod i3c;
pub mod interface_regs;
pub mod lc;
pub mod mbox;
pub mod mci;
pub mod otp;
pub mod primary_flash;
pub mod root_bus;
pub mod secondary_flash;
pub mod sha512_acc;
pub mod soc;
